"""Structured response models for ResearcherAgent."""

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator


class ToolCallStatus(str, Enum):
    """Status of a tool call execution."""

    SUCCESS = "success"
    FAILED = "failed"
    TIMEOUT = "timeout"


class ToolCallRecord(BaseModel):
    """
    Record of a single tool invocation.

    Attributes:
        tool_name: Name of the MCP tool invoked
        parameters: Input parameters passed to the tool
        result: Tool output (None if failed/timeout)
        duration_ms: Execution time in milliseconds
        status: Execution status (success/failed/timeout)
    """

    tool_name: str = Field(
        ..., description="Name of the MCP tool that was invoked", min_length=1
    )
    parameters: dict = Field(..., description="Input parameters passed to the tool")
    result: Optional[Any] = Field(
        None, description="Tool output; None if execution failed or timed out"
    )
    duration_ms: int = Field(..., ge=0, description="Execution time in milliseconds")
    status: ToolCallStatus = Field(
        ..., description="Execution status: SUCCESS, FAILED, or TIMEOUT"
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "tool_name": "web_search",
                "parameters": {"query": "capital of France", "max_results": 5},
                "result": [
                    {
                        "title": "Paris - Wikipedia",
                        "url": "https://...",
                        "snippet": "Paris is the capital...",
                    }
                ],
                "duration_ms": 1234,
                "status": "SUCCESS",
            }
        }
    )


class FinalAnswer(BaseModel):
    """Minimal structured output from the LLM.
    
    This model is what the LLM actually generates. Infrastructure
    metadata (tool calls, durations, status) is added separately by
    combining this with ToolCallRecord logs.
    
    Attributes:
        answer: The final answer to the user's query
        confidence: Model's self-assessed confidence (0.0-1.0)
    """

    answer: str = Field(
        ..., description="The final answer to the user's query", min_length=1
    )
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0"
    )

    @field_validator("confidence")
    @classmethod
    def validate_confidence(cls, v: float) -> float:
        """Ensure confidence is within valid range."""
        if not 0.0 <= v <= 1.0:
            raise ValueError("Confidence must be between 0.0 and 1.0")
        return v


class AgentResponse(BaseModel):
    """
    Complete agent response with infrastructure metadata.

    This is constructed AFTER agent execution by combining:
    - LLM output (FinalAnswer)
    - Tool call logs from infrastructure (_get_tool_log())

    Attributes:
        answer: The final answer to the user's query
        tool_calls: List of all tool invocations made during execution
        confidence: Model's self-assessed confidence (0.0-1.0)
    """

    answer: str = Field(
        ..., description="The final answer to the user's query", min_length=1
    )
    tool_calls: List[ToolCallRecord] = Field(
        default_factory=list,
        description="All tool invocations made during agent execution",
    )
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0"
    )

    @field_validator("confidence")
    @classmethod
    def validate_confidence(cls, v: float) -> float:
        """Ensure confidence is within valid range."""
        if not 0.0 <= v <= 1.0:
            raise ValueError("Confidence must be between 0.0 and 1.0")
        return v

    @classmethod
    def from_llm_output(
        cls, llm_output: "FinalAnswer", tool_calls: List[ToolCallRecord]
    ) -> "AgentResponse":
        """Construct AgentResponse from LLM output + infrastructure logs.
        
        Args:
            llm_output: The FinalAnswer generated by the LLM
            tool_calls: Tool call records from infrastructure logging
            
        Returns:
            Complete AgentResponse with both LLM output and execution metadata
        """
        return cls(
            answer=llm_output.answer,
            confidence=llm_output.confidence,
            tool_calls=tool_calls,
        )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "answer": "Paris",
                "tool_calls": [
                    {
                        "tool_name": "web_search",
                        "parameters": {"query": "capital of France", "max_results": 5},
                        "result": [
                            {
                                "title": "Paris - Wikipedia",
                                "url": "...",
                                "snippet": "...",
                            }
                        ],
                        "duration_ms": 1234,
                        "status": "SUCCESS",
                    }
                ],
                "confidence": 0.95,
            }
        }
    )
